### ISSUE TITLE
Using Torch YOLOv7 Attribute

### ISSUE THREAD

**Issue by ncbdrck** [Extended-Object-Detection-ROS/extended_object_detection#5]
Hi,

I tried setting up the package to use `Torch YOLOv7 Attribute` by installing the `Libtorch` package. I followed the instructions given in the [Libtorch_install](https://github.com/Extended-Object-Detection-ROS/wiki_english/wiki/Libtorch_install) page and made the necessary additions to the `CMakeLists.txt` of the `extended_object_detection` package as below.

```
## Optional parts of library
set(opencv_contrib OFF)
set(zbar_lib OFF)
set(DLib OFF)
set(igraph OFF)
set(torch ON)
set(OAK OFF

if(torch)
    #set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}/home/jay/Libs/libtorch")
    list(APPEND CMAKE_PREFIX_PATH "/home/jay/Libs/libtorch")
    message(${CMAKE_PREFIX_PATH})
    find_package(Torch REQUIRED)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")    
endif(torch)
``` 

However, I get errors when I build the workspace.

Since the `Libtorch` versions are not mentioned on the page, I tried the following variations. But was unable to build the workspace. 
- libtorch-shared-with-deps-latest
- libtorch-shared-with-deps-2.3.0+cpu
- libtorch-shared-with-deps-2.3.0+cu121
- libtorch-cxx11-abi-shared-with-deps-2.3.0+cu121
- libtorch-shared-with-deps-1.0.0

Most of them end like the following.

![image](https://github.com/Extended-Object-Detection-ROS/extended_object_detection/assets/14373193/0d4c87ac-96e8-485a-957b-633665921630)

Can you please help me with resolving this issue?

Thanks,
Jay

**Comment by MoscowskyAnton** [comment]
Hi, @ncbdrck , thanks for mention that!
I will update information about libtorch in few days, hope this will help, please stay tuned

**Comment by MoscowskyAnton** [comment]
@ncbdrck I pushed huge update from my private repository, you can try it now (please update the master branch)
By the way I am successfully using 2.1.2+cpu version of libtorch

**Comment by ncbdrck** [comment]
Hi @MoscowskyAnton Thank you very much for the update. I tried cloning the repo, but I cannot clone the lib submodule (extended_object_detection/src/lib). Can you please check it?

Thanks,
Jay

**Comment by MoscowskyAnton** [comment]
@ncbdrck my bad, just fixed, you are very welcome for try )

**Comment by ncbdrck** [comment]
Thanks, it is now working.
